- id: detect-secrets
  name: Detect secrets
  description: Detects high entropy strings that are likely to be passwords.
  entry: detect-secrets-hook
  language: python
  # for backward compatibility
  files: .*

- id: doc8
  name: doc8
  description: This hook runs doc8 for linting docs
  entry: doc8
  language: python
  files: \.rst$
  require_serial: true
