name: test

permissions:
  contents: read
  pull-requests: write

on: [push, pull_request]

jobs:
  # --------------------------------------------------------------------------
  # Pre-commit
  # --------------------------------------------------------------------------
  pre-commit:
    name: pre-commit ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 5
      matrix:
        os:
          - ubuntu-22.04
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install detect-secrets and deps
        run: pip install detect-secrets doc8 ruff black pip --upgrade
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  # --------------------------------------------------------------------------
  # Python 3.9-3.14
  # --------------------------------------------------------------------------
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        pip install -e .[all]
    - name: Run Tests
      run: pytest
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Run Tests

  # --------------------------------------------------------------------------
  # Finish
  # --------------------------------------------------------------------------
  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        debug: True
